### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by marcelog09** [artplayrpg/gamemode#1]
Estou recebendo esse erro:

database.inc(10) : fatal error 100: cannot read from file: "env"

Está faltando o arquivo env.inc, não?

**Comment by eiskye** [comment]
Pra você está compilando o gamemode você precisa usar o sampctl. 

Depois de ter feito a instalação do mesmo, navegue até a pasta do projeto e execute os comandos abaixo na sequência:

```
sampctl package ensure
sampctl package build
sampctl package run
```
Amanhã estarei reformulando o método de inclusão dos módulos para que não fique dependendo do sampctl para compilar e usar o projeto. Também estarei documentando o projeto e realizando os commits de alguns sistemas novos.

**Comment by marcelog09** [comment]
Entendi, não tinha conhecimento do sampctl. Eu consegui resolver de uma outra maneira, para estudar e entender o funcionamento modular, inclusive, este projeto me fez ter coragem para fazer um GM do 0 e modular, pois o do meu servidor é de 2011, passou na mão de 3 pessoas que programavam de forma diferente e, possui mais de 100 mil linhas em um só arquivo, ou seja, muito bagunçado e desotimizado, realmente está mais fácil refazer do 0.

Não desista deste projeto, pois com certeza irá ajudar muitas outras pessoas também!
